import oracledb from 'oracledb';

const dbConfig = {
  user: process.env.DB_USER || 'system',
  password: process.env.DB_PASSWORD || 'Pusd4t1n2025',
  connectString: process.env.DB_CONNECT_STRING || '10.15.38.162:1539/FREEPDB1',
};

// Create tables if not exists
const createTablesSQL = {
  masterUnit: `
    CREATE TABLE WEBSITE_JAKHABITAT_MASTER_UNIT (
      ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      NAMA_UNIT VARCHAR2(255) NOT NULL,
      LOKASI VARCHAR2(255) NOT NULL,
      TIPE_UNIT VARCHAR2(50) NOT NULL,
      TIPE VARCHAR2(50) NOT NULL,
      LUAS NUMBER NOT NULL,
      DESKRIPSI CLOB,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  `,
  masterHarga: `
    CREATE TABLE WEBSITE_JAKHABITAT_MASTER_HARGA (
      ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      UNIT_ID NUMBER NOT NULL,
      HARGA_JUAL NUMBER NOT NULL,
      HARGA_SEWA NUMBER,
      DP_MINIMUM NUMBER DEFAULT 20,
      BUNGA_TAHUNAN NUMBER DEFAULT 12,
      CICILAN_5TH NUMBER,
      CICILAN_7TH NUMBER,
      CICILAN_10TH NUMBER,
      CICILAN_11TH NUMBER,
      CICILAN_15TH NUMBER,
      CICILAN_20TH NUMBER,
      CICILAN_25TH NUMBER,
      CICILAN_30TH NUMBER,
      DISKON NUMBER DEFAULT 0,
      TANGGAL_MULAI DATE,
      TANGGAL_BERAKHIR DATE,
      KETERANGAN CLOB,
      STATUS VARCHAR2(20) DEFAULT 'Aktif',
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT FK_JAKHABITAT_UNIT_HARGA FOREIGN KEY (UNIT_ID) REFERENCES WEBSITE_JAKHABITAT_MASTER_UNIT(ID)
    )
  `
};

export async function initMasterTables() {
  let connection;
  try {
    connection = await oracledb.getConnection(dbConfig);
    
    // Check and create WEBSITE_JAKHABITAT_MASTER_UNIT table
    const unitResult = await connection.execute(
      `SELECT COUNT(*) as count FROM user_tables WHERE table_name = 'WEBSITE_JAKHABITAT_MASTER_UNIT'`
    );
    
    if (unitResult.rows[0][0] === 0) {
      await connection.execute(createTablesSQL.masterUnit);
      console.log('Table WEBSITE_JAKHABITAT_MASTER_UNIT created successfully');
    }
    
    // Check and create WEBSITE_JAKHABITAT_MASTER_HARGA table
    const hargaResult = await connection.execute(
      `SELECT COUNT(*) as count FROM user_tables WHERE table_name = 'WEBSITE_JAKHABITAT_MASTER_HARGA'`
    );
    
    if (hargaResult.rows[0][0] === 0) {
      await connection.execute(createTablesSQL.masterHarga);
      console.log('Table WEBSITE_JAKHABITAT_MASTER_HARGA created successfully');
    }
  } catch (error) {
    console.error('Master tables initialization error:', error);
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

// MASTER UNIT CRUD
export async function createUnit(unitData) {
  let connection;
  try {
    connection = await oracledb.getConnection(dbConfig);
    
    const result = await connection.execute(
      `INSERT INTO WEBSITE_JAKHABITAT_MASTER_UNIT (NAMA_UNIT, LOKASI, TIPE_UNIT, TIPE, LUAS, DESKRIPSI) 
       VALUES (:namaUnit, :lokasi, :tipeUnit, :tipe, :luas, :deskripsi)`,
      {
        namaUnit: unitData.namaUnit,
        lokasi: unitData.lokasi,
        tipeUnit: unitData.tipeUnit,
        tipe: unitData.tipe,
        luas: unitData.luas,
        deskripsi: unitData.deskripsi
      },
      { autoCommit: true, outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    
    return result;
  } catch (error) {
    throw error;
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

export async function getUnits() {
  let connection;
  try {
    connection = await oracledb.getConnection(dbConfig);
    
    const result = await connection.execute(
      `SELECT ID, NAMA_UNIT, LOKASI, TIPE_UNIT, TIPE, LUAS, DESKRIPSI, CREATED_AT 
       FROM WEBSITE_JAKHABITAT_MASTER_UNIT 
       ORDER BY CREATED_AT DESC`,
      {},
      { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    
    return result.rows.map(row => ({
      id: row.ID,
      namaUnit: row.NAMA_UNIT,
      lokasi: row.LOKASI,
      tipeUnit: row.TIPE_UNIT,
      tipe: row.TIPE,
      luas: row.LUAS,
      deskripsi: row.DESKRIPSI,
      createdAt: row.CREATED_AT
    }));
  } catch (error) {
    throw error;
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

export async function updateUnit(id, unitData) {
  let connection;
  try {
    connection = await oracledb.getConnection(dbConfig);
    
    const result = await connection.execute(
      `UPDATE WEBSITE_JAKHABITAT_MASTER_UNIT 
       SET NAMA_UNIT = :namaUnit, LOKASI = :lokasi, TIPE_UNIT = :tipeUnit, 
           TIPE = :tipe, LUAS = :luas, DESKRIPSI = :deskripsi, UPDATED_AT = CURRENT_TIMESTAMP
       WHERE ID = :id`,
      {
        id: id,
        namaUnit: unitData.namaUnit,
        lokasi: unitData.lokasi,
        tipeUnit: unitData.tipeUnit,
        tipe: unitData.tipe,
        luas: unitData.luas,
        deskripsi: unitData.deskripsi
      },
      { autoCommit: true, outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    
    return result;
  } catch (error) {
    throw error;
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

export async function deleteUnit(id) {
  let connection;
  try {
    connection = await oracledb.getConnection(dbConfig);
    
    const result = await connection.execute(
      `DELETE FROM WEBSITE_JAKHABITAT_MASTER_UNIT WHERE ID = :id`,
      { id },
      { autoCommit: true, outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    
    return result;
  } catch (error) {
    throw error;
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

// MASTER HARGA CRUD
export async function createHarga(hargaData) {
  let connection;
  try {
    connection = await oracledb.getConnection(dbConfig);
    
    const result = await connection.execute(
      `INSERT INTO WEBSITE_JAKHABITAT_MASTER_HARGA 
       (UNIT_ID, HARGA_JUAL, HARGA_SEWA, DP_MINIMUM, BUNGA_TAHUNAN, 
        CICILAN_5TH, CICILAN_7TH, CICILAN_10TH, CICILAN_11TH, CICILAN_15TH, 
        CICILAN_20TH, CICILAN_25TH, CICILAN_30TH, DISKON, TANGGAL_MULAI, 
        TANGGAL_BERAKHIR, KETERANGAN, STATUS) 
       VALUES (:unitId, :hargaJual, :hargaSewa, :dpMinimum, :bungaTahunan,
               :cicilan5th, :cicilan7th, :cicilan10th, :cicilan11th, :cicilan15th,
               :cicilan20th, :cicilan25th, :cicilan30th, :diskon, :tanggalMulai,
               :tanggalBerakhir, :keterangan, :status)`,
      hargaData,
      { autoCommit: true, outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    
    return result;
  } catch (error) {
    throw error;
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

export async function getHarga() {
  let connection;
  try {
    connection = await oracledb.getConnection(dbConfig);
    
    const result = await connection.execute(
      `SELECT h.ID, h.UNIT_ID, u.NAMA_UNIT, u.LOKASI, u.TIPE_UNIT, u.LUAS,
              h.HARGA_JUAL, h.HARGA_SEWA, h.DP_MINIMUM, h.BUNGA_TAHUNAN,
              h.CICILAN_5TH, h.CICILAN_7TH, h.CICILAN_10TH, h.CICILAN_11TH,
              h.CICILAN_15TH, h.CICILAN_20TH, h.CICILAN_25TH, h.CICILAN_30TH,
              h.DISKON, h.STATUS, h.CREATED_AT
       FROM WEBSITE_JAKHABITAT_MASTER_HARGA h
       JOIN WEBSITE_JAKHABITAT_MASTER_UNIT u ON h.UNIT_ID = u.ID
       ORDER BY h.CREATED_AT DESC`,
      {},
      { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    
    return result.rows.map(row => ({
      id: row.ID,
      unitId: row.UNIT_ID,
      namaUnit: row.NAMA_UNIT,
      lokasi: row.LOKASI,
      tipeUnit: row.TIPE_UNIT,
      luas: row.LUAS,
      hargaJual: row.HARGA_JUAL,
      hargaSewa: row.HARGA_SEWA,
      dpMinimum: row.DP_MINIMUM,
      bungaTahunan: row.BUNGA_TAHUNAN,
      cicilan5th: row.CICILAN_5TH,
      cicilan7th: row.CICILAN_7TH,
      cicilan10th: row.CICILAN_10TH,
      cicilan11th: row.CICILAN_11TH,
      cicilan15th: row.CICILAN_15TH,
      cicilan20th: row.CICILAN_20TH,
      cicilan25th: row.CICILAN_25TH,
      cicilan30th: row.CICILAN_30TH,
      diskon: row.DISKON,
      status: row.STATUS,
      createdAt: row.CREATED_AT
    }));
  } catch (error) {
    throw error;
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

export async function updateHarga(id, hargaData) {
  let connection;
  try {
    connection = await oracledb.getConnection(dbConfig);
    
    const result = await connection.execute(
      `UPDATE WEBSITE_JAKHABITAT_MASTER_HARGA 
       SET UNIT_ID = :unitId, HARGA_JUAL = :hargaJual, HARGA_SEWA = :hargaSewa,
           DP_MINIMUM = :dpMinimum, BUNGA_TAHUNAN = :bungaTahunan,
           CICILAN_5TH = :cicilan5th, CICILAN_7TH = :cicilan7th, 
           CICILAN_10TH = :cicilan10th, CICILAN_11TH = :cicilan11th,
           CICILAN_15TH = :cicilan15th, CICILAN_20TH = :cicilan20th,
           CICILAN_25TH = :cicilan25th, CICILAN_30TH = :cicilan30th,
           DISKON = :diskon, TANGGAL_MULAI = :tanggalMulai,
           TANGGAL_BERAKHIR = :tanggalBerakhir, KETERANGAN = :keterangan,
           STATUS = :status, UPDATED_AT = CURRENT_TIMESTAMP
       WHERE ID = :id`,
      { ...hargaData, id },
      { autoCommit: true, outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    
    return result;
  } catch (error) {
    throw error;
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

export async function deleteHarga(id) {
  let connection;
  try {
    connection = await oracledb.getConnection(dbConfig);
    
    const result = await connection.execute(
      `DELETE FROM WEBSITE_JAKHABITAT_MASTER_HARGA WHERE ID = :id`,
      { id },
      { autoCommit: true, outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    
    return result;
  } catch (error) {
    throw error;
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}